#ifndef CONSTS_H
#define CONSTS_H

#define BOARD_WIDTH 15
#define BOARD_HEIGHT 30

#define BOARD_TILE_SIZE 64

#define SETTINGS_ORGNIZATION "kidney6-323"
#define SETTINGS_APPLICATION "hexakis"

#define SETTINGS_DROPPREVIEW_DEFAULT false
#define SETTINGS_INTERVAL_DEFAULT 500

#endif // CONSTS_H
